ALTER TABLE users DROP CONSTRAINT IF EXISTS users_role_check;

ALTER TABLE users ADD CONSTRAINT users_role_check CHECK (role IN ('ADMIN', 'USER'));

ALTER TABLE users ALTER COLUMN role SET DEFAULT 'USER';

ALTER TABLE users ALTER COLUMN role SET NOT NULL;
